"""many to many posts episodes

Revision ID: 461852330cee
Revises: faefba07f978
Create Date: 2026-02-01 18:21:33.396805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461852330cee'
down_revision: Union[str, Sequence[str], None] = 'faefba07f978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_episodes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'episode_id')
    )
    # Migrate existing post-episode relationships before dropping the column
    op.execute("INSERT INTO post_episodes (post_id, episode_id) SELECT id, episode_id FROM posts WHERE episode_id IS NOT NULL")
    op.drop_index(op.f('ix_posts_episode_id'), table_name='posts')
    op.drop_constraint(op.f('posts_episode_id_fkey'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'episode_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('episode_id', sa.UUID(), autoincrement=False, nullable=True))
    # Restore post-episode relationships (takes most recent episode for each post)
    op.execute("""
        UPDATE posts SET episode_id = pe.episode_id
        FROM (SELECT DISTINCT ON (post_id) post_id, episode_id FROM post_episodes) pe
        WHERE posts.id = pe.post_id
    """)
    op.create_foreign_key(op.f('posts_episode_id_fkey'), 'posts', 'episodes', ['episode_id'], ['id'])
    op.create_index(op.f('ix_posts_episode_id'), 'posts', ['episode_id'], unique=False)
    op.drop_table('post_episodes')
    # ### end Alembic commands ###
