"""simplify user model for rss

Revision ID: 90ba26a1e517
Revises: 4162b04ce3b8
Create Date: 2026-01-16 22:50:41.868036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ba26a1e517'
down_revision: Union[str, Sequence[str], None] = '4162b04ce3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.drop_column('users', 'refresh_token_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_encrypted', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
