"""remove multi-user tables

Revision ID: 95223ba9cf30
Revises: 90ba26a1e517
Create Date: 2026-01-16 22:51:57.329201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95223ba9cf30'
down_revision: Union[str, Sequence[str], None] = '90ba26a1e517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_post_history_user_post'), table_name='user_post_history')
    op.drop_table('user_post_history')
    op.drop_index(op.f('ix_user_subreddits_user_subreddit'), table_name='user_subreddits')
    op.drop_table('user_subreddits')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reddit_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('reddit_username', name=op.f('users_reddit_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_subreddits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subreddit', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_subreddits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_subreddits_pkey'))
    )
    op.create_index(op.f('ix_user_subreddits_user_subreddit'), 'user_subreddits', ['user_id', 'subreddit'], unique=True)
    op.create_table('user_post_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('used_in_episode_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('user_post_history_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_post_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_post_history_pkey'))
    )
    op.create_index(op.f('ix_user_post_history_user_post'), 'user_post_history', ['user_id', 'post_id'], unique=True)
    # ### end Alembic commands ###
