"""add episode_id to posts

Revision ID: c1cc2c9433cb
Revises: e84de4a35680
Create Date: 2026-01-20 18:38:27.600707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cc2c9433cb'
down_revision: Union[str, Sequence[str], None] = 'e84de4a35680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('episode_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_posts_episode_id'), 'posts', ['episode_id'], unique=False)
    op.create_foreign_key('posts_episode_id_fkey', 'posts', 'episodes', ['episode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_episode_id_fkey', 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_episode_id'), table_name='posts')
    op.drop_column('posts', 'episode_id')
    # ### end Alembic commands ###
