"""remove num_comments column

Revision ID: faefba07f978
Revises: c1cc2c9433cb
Create Date: 2026-01-31 14:15:45.500309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faefba07f978'
down_revision: Union[str, Sequence[str], None] = 'c1cc2c9433cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'num_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('num_comments', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
